### ISSUE TITLE
Fov doesn't work in some situations

### ISSUE THREAD

**Issue by AnotherManOfCulture** [lanylow/genshin-utility#39]
The fov resets every time you pass through one of these rings or when you speed up the boat. The first ring is in some puzzles, it's very difficult to do with the fov increasing and decreasing with each ring you pass.

https://i.ibb.co/j827sVh/f1.png
https://i.ibb.co/2jgQtpt/f2.png
https://i.ibb.co/nP0YByR/b.png

**Comment by lanylow** [comment]
Hello, I have came up with a working solution that I tested while speeding up the boat, I didn't test the rings because I have no idea where they are. I'm not sure if this fix won't negatively affect the FOV in other areas of the game and I don't really have the time to test it, so if you could please use this library file next time you play and give me feedback.
[library.zip](https://github.com/lanylow/genshin-utility/files/12834957/library.zip)

**Comment by AnotherManOfCulture** [comment]
I tested it here, it worked perfectly for the boat and one of the rings, only the second ring with the "swirl" aspect keeps losing Fov, honestly it's not a big problem, the main one was the other two, apart from that I haven't seen anything else affected by the changes.

Thank you very much, if you want to try to fix the "swirl" it is located here:

[https://i.ibb.co/DDGDG15/swirl.png](https://i.ibb.co/DDGDG15/swirl.png)

Just dive in front of the teleport.

**Comment by lanylow** [comment]
I assume this is somewhere in the new areas? If so, I can't really do anything because I don't have them unlocked.

**Comment by AnotherManOfCulture** [comment]
Yeah, it's in Fontaine. But no problem, I'll close the issue, if at some point you decide to fix it you can reopen it. 

Thank you!
