### ISSUE TITLE
Postbuild error if out folder doesn't exist

### ISSUE THREAD

**Issue by z3lx** [lanylow/genshin-utility#53]
First of all, many thanks for actively maintaining the project!

Using CMake and Visual Studio 17 2022 as the generator produces the following error when compiling:

![err](https://github.com/user-attachments/assets/d326027d-52ac-4aac-bb5d-5046fcf257b9)

This can be fixed by creating the out folder manually, but why not use the CMake install path instead?

**Comment by lanylow** [comment]
Hello. I just noticed this issue today too when updating the tool. I guess this was my first time deleting that folder ever since I added CMake. Anyway, I'm probably going to fix it in the next update.

And answering the question, that folder is indeed pointless now, but a long time ago when the loader was being built with CMake too, it'd create two separate folders for these projects, so I just added this command to copy both files into one folder. I suppose I should do this with the current loader too, but I never bothered because I just built it once and left it in the `out` folder as it rarely changed anyway.
