### ISSUE TITLE
Error 31-4302

### ISSUE THREAD

**Issue by THANG1344** [lanylow/genshin-utility#58]
i got this error every time i use the fps unlocker, it required to delete the game and download from official source, 
But when I don't use the fps unlocker, I can log into the game

**Comment by Imperial-Egineer** [comment]
Same situation here bro cant play the game everytime I use the unlocker. With no Unlocker it works fine. Up for this issue. I hope this will be resolved

**Comment by z3lx** [comment]
This issue can be (partially) fixed by enabling the function hook after the game launches, specifically in the loading screen of domains. I've release a [hotfix](https://github.com/z3lx/genshin-fov-unlock/releases/tag/v1.1.3-hotfix) in my own re-implementation of this repo's FOV unlocker that allows you to do just that. It's an ugly workaround, but it will have to do.

**Comment by Imperial-Egineer** [comment]
any update?

**Comment by lanylow** [comment]
Fixed in the [latest release](https://github.com/lanylow/genshin-utility/releases/tag/v1.5.9).
